apiVersion: apps/v1
kind: Deployment
metadata:
  name: hamzaci-app
  labels:
    app: hamzaci-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hamzaci-app
  template:
    metadata:
      labels:
        app: hamzaci-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest  # Use the Nginx Docker image
          ports:
            - containerPort: 80  # Nginx default port is 80
